---
abstract: 'Pack your dependencies onto your script file'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  Carp: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Scalar::Util: '0'
  Test::More: '0.94'
  ok: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-FatPacker
provides:
  Dist::Zilla::Plugin::FatPacker:
    file: lib/Dist/Zilla/Plugin/FatPacker.pm
    version: '1.141200'
requires:
  App::FatPacker: '0'
  Dist::Zilla: '0'
  Dist::Zilla::Role::FileMunger: '0'
  File::Path: '0'
  File::Temp: '0'
  Moose: '0'
  ok: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-FatPacker
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-FatPacker/
  repository: git://github.com/doherty/Dist-Zilla-Plugin-FatPacker.git
version: '1.141200'
