---
abstract: 'pack your dependencies onto your script file'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-FatPacker
provides:
  Dist::Zilla::Plugin::FatPacker:
    file: lib/Dist/Zilla/Plugin/FatPacker.pm
    version: 1.100841
requires:
  App::FatPacker: 0
  Carp: 0
  Dist::Zilla::Role::FileMunger: 0
  English: 0
  File::Find: 0
  File::Path: 0
  File::Temp: 0
  Moose: 0
  Scalar::Util: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-FatPacker
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-FatPacker/
  repository: http://github.com/hanekomu/Dist-Zilla-Plugin-FatPacker
version: 1.100841
